### ISSUE TITLE
Website Update

### ISSUE THREAD

**Issue by mohamed7afezz** [mohamed7afezz/itsmart#1]
Plz add the Issues for  current of website here listed as check boxes 💃 

Link: http://www.itsmart.online/

**Comment by mohamed7afezz** [comment]
- [ ]

**Comment by ElsayedAtef** [comment]
1- edit the location to Nasr city, Cairo and add a mobile  number and add https://twitter.com/ItsmartOnline 
2-دي هتحطها في هيا ايه الشركه في الكلام الموجود علي الصوره الي تحت 
--------------------
it-smart is your IT partner for success through advanced integrated technical solutions, it-smart develops clients’ businesses help them effectively run it. Our IT services include Web Hosting, IT Consultancy, IT Outsourcing, Software Development. We follow a thorough analytical approach to analyze clients’ needs and come up with the most innovative solutions customized to meet their needs. Our services are supported by superb after-sales services to ensure client satisfaction and success.
---------------------
3-our services:-
----------**web hosting**
Hosting services are considered of the utmost vital pillars for the success of websites and applications. In it-smart, we are specialized in providing premium quality dedicated web hosting solutions combining Arabian culture with global quality standards. We adopt top-notch technological tools and techniques to provide the most efficient performance to your distinguished website 24/7. This is only possible because we have our own servers which utilize the best infrastructure in multi geo-locations in the Middle East, Europe, and the USA.
-----------------
----------- **IT Consultancy**
IT field is enormous and ever-changing, making it harder to get skilled manpower covering all your technical needs. it-smart helps you focus on your core business through providing IT Outsourcing Services.

We focus on the service quality and client satisfaction through providing Top notch employees in the IT field. Our mission is to get the job done quicker and smarter to overcome your business challenges and achieve your targeted results. Why you can depend on Us?

Because we wok, in it-smart, on providing the best calibers to enable you to reach your competitive goals in the market. That’s why we are considered one of the best companies providing IT outsourcing in the Middle East.
---------------
--------------------------**IT Outsourcing**
IT field is enormous and ever-changing, making it harder to get skilled manpower covering all your technical needs. it-smart helps you focus on your core business through providing IT Outsourcing Services.

We focus on the service quality and client satisfaction through providing Top notch employees in the IT field. Our mission is to get the job done quicker and smarter to overcome your business challenges and achieve your targeted results.

Advantages of our services in IT Outsourcing

    Process efficiencies ensuring a lower cost process delivery
    High levels of Commitment
    Quick response to your requirements.
    Qualified experts who will achieve the best results
    Best service standards
    Scalable and flexible plans for future growth
---------------- 
------------------ **Software Development**
We, in it-smart, employ our profound knowledge of the changing market requirements and the latest Technology updates to develop custom solutions matching your needs and work challenges so we are providing Software Development Service.

Our Software Development Services are flexible and effective to empower you to:

    Implement strategies
    Achieve your goals
    Improve productivity
    Accomplish cost efficiency
    Improve Return on Investment (ROI)

Software-Development
Our Software Development Service:

We in it-smart provide the best Software Development Services including:

    Developing Custom Software Systems
    Web and Portal Development
    Mobile Application Development
    Resolve Cloud Application Development
    Archiving Systems
    Enterprise content management system
    E-commerce solutions
    Integration and migration for Enterprise systems and software
    Enterprise Resource Planning (ERP)

We have a team of professionally certified experts and talented developers with years of experience and up-to-date technology knowledge, who work on delivering software which is:

    Innovation
    High quality
    Ease of use
    Integration with other solutions

 How do we achieve the Best for You?

    Listen carefully to your needs
    Think and analyze your requirements
    Set vision and objectives
    Execute and provide strategies with magnificent quality and creativity
    Do and implement the required updates smoothly& in a fast way
    Evaluate and measure solutions’ success and your satisfaction about it

And thus, we achieve the Promised Success
